### ISSUE TITLE
[BUG] Incorrect mailer daemon for more domains

### ISSUE THREAD

**Issue by dominch** [Mailu/helm-charts#112]
**Describe the bug**
I deployed this chart with main domain `example.com` and added new domain `myexample.com`. Then created mailbox `user@myexample.com` and test sending mails to fake/incorrect email address. I quickly get reply from `MAILER-DAEMON@example.com` with error message. It should reply from same domain as user domain. 

**Environment**
- k3s 

**Additional context**
I think this is caused by single postfix pod with my domain setting. It may be needed to deploy more those pods just to send correct mailer-daemon address. I could not find any information about that in docs. Just need to isolate two groups of users.

**Comment by micw** [comment]
Hello,
IMO this is expected behaviour. Bounce messages always come from $myhostname which is by default the 1st configured domain name. There is no way to have one MTA more than $myhostname, so if you need this, you'd need to set up more than one MTA (on more than one IP addresses) which is out of scope of this helm chart.
