### ISSUE TITLE
roudcube not login

### ISSUE THREAD

**Issue by mjhasani** [Mailu/helm-charts#138]
After installation, not able to login to webmail.
The roundcube pod logs are:

 <a978405f> IMAP Error: Login failed for info against mailu-front from 10.244.4.79(X-Real-IP: 10.244.5.43,X-Forwarded-For: 10.244.0.0, 10.244.5.43). AUTHENTICATE PLAIN: Authentication credentials invalid in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)

**Comment by micw** [comment]
After installation you can only log-in to admin. You need to create domains/users first, then you can log into webmail.
Which helm chart version and mailu version are you using?

**Comment by mjhasani** [comment]
Tanks micw,
I had created info user and then tried to login but got IMAP Error...

**Comment by ZuSe** [comment]
Hi @mjhasani  did you solve the issue?
We are running into the same problem. 

Version: 1.9.26

**Comment by mjhasani** [comment]
Hi @ZuSe, we still could not solve the problem.

**Comment by mcsmgs** [comment]
We had the exact same issue. Turns out we were using the wrong `SUBNET` values for the [POD Subnets](https://github.com/Mailu/helm-charts/tree/master/mailu#all-services-are-running-but-authentication-fails-for-webmail-and-imap). Once the subnet values matched the k8s cluster POD IP subnet  Dovecot started passing the imap auth requests again.
```Jan 12 11:57:16 imap-login: Info: Login: user=<mailadmin@test.net>, method=PLAIN, rip=10.2.103.228, lip=10.2.103.157, mpid=313, session=<vX560Q/yvJoKAmfk>```
