### ISSUE TITLE
Missing containers on Docker Hub

### ISSUE THREAD

**Issue by albertkohl-monotek** [Mailu/helm-charts#213]
**Describe the bug**
image pull fails due t docker repo move

**Environment**
microk8s

**Additional context**
i noticed today that my mailu setup is not running. i used a helm chart to deploy 1.9.10. it appears that you guys moved the repo to github, but i dont see any images for 1.9. `[https://github.com/Mailu/Mailu/issues/2704](url)` 

is there any way to get those images posted as well so i can get mail up and runing?

secondary question, are their any plans on releasing a 2.0 helm chart?

Thanks!

**Comment by oleksandr-mazur** [comment]
Change repository in your values

Example:
`mailuVersion: 1.9.50

admin:
  image:
    repository: ghcr.io/mailu/admin


postfix:
  image:
    repository: ghcr.io/mailu/postfix


dovecot:
  image:
    repository: ghcr.io/mailu/dovecot


rspamd:
  image:
    repository: ghcr.io/mailu/rspamd

clamav:
  image:
    repository: ghcr.io/mailu/clamav

roundcube:
  image:
    repository: ghcr.io/mailu/roundcube

webdav:
  image:
    repository: ghcr.io/mailu/radicale


fetchmail:
  image:
    repository: ghcr.io/mailu/fetchmail`

**Comment by fastlorenzo** [comment]
Release 1.0.0 has ghcr.io as default repository

**Comment by albertkohl-monotek** [comment]
That worked, thanks! my helm version was set to 1.9.10 and i was getting errors that it didnt exist, so i thought you didnt publish the v1 images based off what i saw in ghcr, but i might have been looking at that wrong. 

if i wanted to bump to 2.0+ do i just do the same w/ the helm chart? if i'm not doing anything crazy in my helm chart, is it a simple upgrade? or any got-cha's i should keep an eye out for?

thanks!

**Comment by lknite** [comment]
Tried changing 'global.imageRegistry: ghcr.io', shouldn't that work rather than specifying each image path individually?

**Comment by fastlorenzo** [comment]
> Tried changing 'global.imageRegistry: ghcr.io', shouldn't that work rather than specifying each image path individually? (but it didn't)

It won't work as v0.3.3 of the chart didn't use `global.imageRegistry`. FYI this won't work either if you want to change the registry for Mailu components in v1.x of the chart. 
If you want to change the registry for the Mailu images in v1.x of the chart, use `imageRegistry` (default is `ghcr.io`)

**Comment by micw** [comment]
@jamesarbrown I understand your complaints about the images but that's not about the helm chart, it's about mailu. The best place to discuss this is the mailu matrix chat. Personally I understand both sides, mailu's (because docker inc made a change that cannot be answered other than dropping it) and yours (since your services are interrupted).

I have checked the chart source. There is no `mailu/templates/fetchmail/deployment.yaml`in the 0.3.x charts, that a feature fro, 1.0.x. It seems that during the merge a build was triggered that released the initial 1.0.x release as 0.3.3.

I have re-released 0.3.3 from the correct branch as well as a 0.3.4 version (that is identical but allows an "upgrade"). Please try this one to get your service running again.

**Comment by micw** [comment]
@fastlorenzo I made some manual pushes to gh-pages to get this sorted. Hope it does not break anything on the new builds.

**Comment by jamesarbrown** [comment]
Hi, I think i have just got it up....... 

- Cloned this repo (created folder helm-charts)
- git checkout old/0.3.x
- went into helm-charts/mailu/templates/fetchmail.yaml and took out the templating lines around line 65 (which was DEBUG and just left it DEBUG true etc)

Then ran an adjusted Helm command to use the local files
`microk8s helm3 upgrade mailu ./helm-charts/mailu --values mailu-values.yaml -n mailu-mailserver`

This server is due to be migrated very very soon, hopefully some more detailed information as TBH no idea where Kubernetes stored the sqllite file.

Also as minor comment, on Chart 1.0.0 the single PVC is not being honoured for rspamd and redis, I am guessing these are now on Bitnami charts?

**Comment by micw** [comment]
> went into helm-charts/mailu/templates/fetchmail.yaml and took out the templating lines around line 65 (which was DEBUG and just left it DEBUG true etc)

Probably no need for this. The issue you had was because there was a completely different chart (1.0.x) in place of 0.3.3.

**Comment by micw** [comment]
I just released 0.3.5 that points to 1.9.50 with the new image locations so that there's a more "official" workaround.

**Comment by micw** [comment]
For reference: https://github.com/Mailu/Mailu/issues/2704

**Comment by micw** [comment]
BTW: the primary reason to remove the old images was to force people to switch to the new repo as long as mailu has access to the docker-hub organization. Due to the change docker inc made, there was a high risk that the organization would be deleted after the grace period which could result in someone else getting control over the docker hub name "mailu" one day. In this case, instead of getting a broken deployment,  you'd got an arbitrary crafted image from an unknown 3rd party on your server.
So IMO deleting the images was the only choice for mailu and should be the choice for any project not willing to pay for docker organizations.

After docker inc received the shit storm the begged for, they reverted the change. But since they clearly showed their true intentions, migration away from that platform should be on anyone's roadmap.

**Comment by fastlorenzo** [comment]
> Also as minor comment, on Chart 1.0.0 the single PVC is not being honoured for rspamd and redis, I am guessing these are now on Bitnami charts

For redis that's indeed the case, for rspamd I'll have to check why it doesn't because this is mailu specific and not using a subchart
