### ISSUE TITLE
Feature request: allow individual PVCs for each pod

### ISSUE THREAD

**Issue by unixfox** [Mailu/helm-charts#39]
Google Cloud persistent disk, AWS EBS, [Longhorn](https://github.com/longhorn/longhorn) and probably more other storage class don't allow a single PVC to be shared between pods in multiple nodes.

This disallows the ability to have each component of Mailu spread on multiple nodes on those platforms due to the one shared PVC.

I would like to know what's the reason behind having one big PVC shared with all the components? Is it really required to have for example the redis component in the same PVC as the admin component? Why can't it be in its own PVC?

That's my thoughts, let me know if I'm wrong about that. If not would it be feasible to have a PVC for each component?

**Comment by micw** [comment]
Historical reasons, the old yamls had it this way and I did not have the time to refactor it.

**Comment by unixfox** [comment]
Oh, I see.
Do you mind if I leave this issue open in case someone wants to rework the chart with separate VPC?

**Comment by micw** [comment]
Sure, I just changed the title accordingly.

**Comment by justinasjaronis** [comment]
I believe at least postfix and dovecot has to share /mail folder to be operational. As Postfix saves mail, and Dovecot serves that mail from mailbox over IMAP/POP3. In my case, way to go would be to use NFS as ReadWriteMany-capable storage provider : https://www.digitalocean.com/community/tutorials/how-to-set-up-readwritemany-rwx-persistent-volumes-with-nfs-on-digitalocean-kubernetes

however using NFS has some other caveats which I tried to document.

**Comment by micw** [comment]
I don't think so. Postfix uses dovecot socket to store mail, so the mail folder must only be accessible by dovecot. From what I know, there's no need to share any filesystem between PODs.

**Comment by justinasjaronis** [comment]
So then the wisest method would be to split volumes in chart to separate PVCs to avoid RWM/NFS at all. wouldn't it be?

**Comment by omitrowski** [comment]
If you don't mind I would fork and workout a solution for this issue. In my opionion either you have one pod having many contianers (postfix, devocot, rspamd, etc) using one PVC, or you have many pods using many PVCs. Anythink else does not make sense in kubernetes.

**Comment by justinasjaronis** [comment]
IMHO one pod with many containers is a very bad practice since you won't be able to use the advantage of cloud computing (i.e. splitting workload across nodes, failover, horizontal scaling etc) so it's not an option. 
Discussing in #54  we have ruled out that no subdirectories in the main PVC have to be shared between different deployments. 

Furthermore, I would highly recommend to keep such files like in /queue/pid/* away from persistent volumes as mentioned below in #54

**Comment by justinasjaronis** [comment]
> If you don't mind I would fork and workout a solution for this issue. In my opionion either you have one pod having many contianers (postfix, devocot, rspamd, etc) using one PVC, or you have many pods using many PVCs. Anythink else does not make sense in kubernetes.

I see sense of mounting /mail from NFS @RWM  in multiple dovecot pods, allowing to scale the setup horizontally.

**Comment by micw** [comment]
> Furthermore, I would highly recommend to keep such files like in /queue/pid/* away from persistent volumes as mentioned below in #54

I disagree, the PID is used for locking which is required for data consistency. No two instances of postfix must access queue at the same time. Nevertheless, a proper cleanup must be done on startup.

**Comment by micw** [comment]
@omitrowski a PR that solves this (by using multiple PVs) is very welcome. Please think about the differnt options the current chart allows for PVs - the change should be as compatible as possible.

**Comment by omitrowski** [comment]
"the end is near", the PR too ;)

**Comment by micw** [comment]
@omitrowski I have seen that you pushed a lot - but into an existing PR with a different scope. Please give me a signal if you're done, the I have a look on it, when we separate it out of the other PR and get it merged.

**Comment by omitrowski** [comment]
@micw yes, "unfortunately" we have a lot of improvements to suggest that we face on every day work. So we do the changes and see how they perform and then improve them. A nightmare to merge it on github, sure. So your help on merging will be very helpful. Going to test the PVC implementation now. I guess we should make branches for the different PRs, what do you think?

**Comment by micw** [comment]
Yes, please create one branch per PR.

**Comment by briantopping** [comment]
I am moving my Mailu instance to a situation where shared volumes are very difficult and decided to take a look at this again. As it stands, mounts use `subPath` on a single shared volume. 

One solution is to merge pods with multiple containers when their PVCs overlap. I attached a mapping of the PVCs paths and the pod they are used by. The `dkim` subpath is the only one that is used in separate pods, all the others are isolated from each other. 

Unfortunately, the two pods that use `dkim` are `admin` and `rspamd`. We can't scale the number of containers within a pod separately from each other, which is to say if either of `admin` and `rspamd` needed to be scaled, both would need to be scaled together. If neither of these **can** be scaled, then there's no problem, but I suspect that they are scaled at different rates in large production deployments. I'll get back to "large production deployments" in a minute.

So then we come back to the question of whether `dkim` really needs to be mounted to both containers. Right now, the admin container seems to be the source to generate signatures and rspamd consumes them. [Rspamd has a means to use Redis](https://rspamd.com/doc/modules/dkim_signing.html), so if admin wrote to Redis instead of the file system, the `dkim` mount would not be required for **either** module and the only shared mount between disparate pods would be removed.

There **is** still a problem when scaling non-disparate pods that require access to the same store, such as Dovecot. We obviously cannot duplicate the mail store for each instance of Dovecot, so in **scaled** instances, a shared filesystem will be required. 

I guess the question for me is how many organizations are running large production deployments of Mailu on Kubernetes. I suspect it's less than 5% of the Kubernetes-based sites that currently need to scale beyond one replica for any pod. Why so low? _Because I bet that nobody is actually using Kubernetes for large production deployments!_ 

If that's the case, here is a plan I have:

- [ ] Change the DKIM store to be in Redis for both the admin and rspamd, remove the `dkim` mounts.
- [ ] Continue to leverage [`.Values.persistence.accessMode`](https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml#L79) such that the deployer may choose to use `ReadWriteMany` if they need to scale pods beyond 1. 
- [ ] Generate one PVC for each of `admin`, `clamav`, `dovecot`, `mailqueue`, `mysql`, `redis`, `roundcube`, `rspamd` and `webdav`.
- [ ] Review the above for situations where the storage needs are only for configuration. When found, remove the PVC and convert the data to a `ConfigMap` mount.

Thoughts?


| subPath | Filename |
| --- | --- |
| admin | admin.yaml |
| clamav | clamav.yaml |
| dkim | admin.yaml |
| dkim | rspamd.yaml |
| dovecotdata | dovecot.yaml |
| dovecotmail | dovecot.yaml |
| mailqueue | postfix.yaml |
| mysql | mysql.yaml |
| redis | redis.yaml |
| roundcube | roundcube.yaml |
| rspamd | rspamd.yaml |
| webdav | webdav.yaml |

**Comment by briantopping** [comment]
Turning on the `combineRspamdAdmin` flag does the following:
- The `rspamd` and `admin` pods are generated with the `combined.yaml` which creates a single pod for the two and shares the `/dkim` mount.
- PVCs are separately generated for each remaining pod that used to take a `subPath` on the share PVC
-- The PVCs have separate `size` and `accessMode` settings. The size is because the split pods will have very different resource requirements, the `accessMode` because not all pods will need to be scaled if the system grows.

It should be enough to get started with.

**Comment by lknite** [comment]
Running into this issue and looking for a solution.  Almost sounds like @briantopping has the fix in place but I don't see it in the values.yaml .  This still being evaluated?  Seems it might be good to have multiple pvcs as the default.

**Comment by micw** [comment]
I finally merged #121. Please do a test with Version 0.2.0 of the chart. If it solves this for you, we can close this issue.

**Comment by zestysoft** [comment]
Oh man, I just finished setting up cephfs to provide this shared access requirement.

So ClamAV doesn't need shared access to the mail files either?  The reason why I ask is that often AV has to play catch up with what's out there, and being able to re-scan the mail files after delivery helps to catch stuff it might have initially missed.

**Comment by briantopping** [comment]
@zestysoft I also used CephFS for a while, found it added more workload to keeping smaller clusters upright. Didn't enjoy the experience, hence the effort. I've been busy with way too much over the summer, apologies for losing track of this. Thrilled it made it in! Thanks @micw!

**Comment by micw** [comment]
Thanks goes to the contributors of this long wanted PR. I only merged it ^^.

**Comment by briantopping** [comment]
> Thanks goes to the contributors of this long wanted PR. I only merged it ^^.

A lot of us worked on it in various forms. I had merged a PR, only to reverse it when unsure about the upgrade path and not wanting to create a bunch of stress. Team effort, thank you for getting it across the line.

**Comment by micw** [comment]
I don't run a multi-pv setup, so any feedback is appreciated if that issue can be closed now.

**Comment by ardimaul** [comment]
> I finally merged #121. Please do a test with Version 0.2.0 of the chart. If it solves this for you, we can close this issue.

Hello i have issue, when there is update (Rolling update) to existing pods that link to a rwo pvc, new pods has spawn but that new pods can't mount existing pvc (because it has mounted to old pods)
Change strategy type to Recreate will fix this

**Comment by micw** [comment]
I create a new issue for the Recreate stuff
